### ISSUE TITLE
Procedure type is not saved when using XML Generator

### ISSUE THREAD

**Issue by botrot** [ESPD/espd#225]
When creating request/response and select the "prodecure type" it appears on the PDF but not in the XML file.

**Comment by ec-mcs** [comment]
Version 1 of the ESPD data model does not have the attribute of procedure type. It is only available in v2. but our ESPD service is using v1. Therefore the PDF shows it correctly but is not in the XML. So, if you would export the XML and open it up again, it would loose the procedure type. As it is fixed in v2, I will close this issue.
